  ros1_bridge:
    container_name: ros1_bridge
    image: ros:galactic-ros1-bridge-focal
    network_mode: host
    command: bash -c "
        source /opt/ros/galactic/setup.bash &&
        source /opt/ros/noetic/setup.bash &&
        ros2 run ros1_bridge dynamic_bridge"
